const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=1200,H=600; canvas.width=W;canvas.height=H;
const keys={}; let running=false,finished=false,startAt=0,last=0,elapsed=0,score=0,stunts=0,boost=0;
const rider={x:90,y:405,vx:0,vy:0,angle:0,spin:0,onGround:false};
const terrain=[{x:0,y:470},{x:165,y:470},{x:230,y:400},{x:315,y:400},{x:370,y:470},{x:470,y:470},{x:535,y:345},{x:625,y:345},{x:690,y:470},{x:760,y:470},{x:815,y:395},{x:885,y:395},{x:950,y:470},{x:1050,y:470},{x:1110,y:350},{x:1200,y:350}];
const obstacles=[{x:185,y:448,w:32,h:22},{x:430,y:443,w:30,h:27},{x:718,y:444,w:29,h:26},{x:1010,y:443,w:32,h:27}];
function reset(){rider.x=90;rider.y=420;rider.vx=0;rider.vy=0;rider.angle=0;rider.spin=0;rider.onGround=false;elapsed=0;score=0;stunts=0;boost=0;finished=false;updateHud()}
function startGame(){reset();running=true;startAt=performance.now();last=startAt;document.getElementById('start-card').classList.add('hidden');document.getElementById('finish-card').classList.add('hidden');requestAnimationFrame(loop)}
function updateHud(){let t=elapsed/1000;document.getElementById('time').textContent=`${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(2).padStart(5,'0')}`;document.getElementById('score').textContent=String(Math.max(0,Math.floor(score))).padStart(6,'0');document.getElementById('stunts').textContent=stunts}
function groundY(x){for(let i=0;i<terrain.length-1;i++){let a=terrain[i],b=terrain[i+1];if(x>=a.x&&x<=b.x)return a.y+(b.y-a.y)*(x-a.x)/(b.x-a.x)}return 470}
function loop(now){if(!running)return;let dt=Math.min((now-last)/1000,.033);last=now;elapsed=now-startAt;update(dt);draw();updateHud();if(rider.x>1140){finish();return}requestAnimationFrame(loop)}
function update(dt){let lean=(keys.ArrowRight?1:0)-(keys.ArrowLeft?1:0);let throttle=keys[' ']||keys.Space; if(throttle&&rider.onGround)boost=Math.min(boost+dt*3,1);else boost=Math.max(0,boost-dt*2);rider.vx+=((throttle?210:0)+lean*18)*dt;rider.vx-=rider.vx*.19*dt;rider.vx=Math.max(45,Math.min(rider.vx,260+boost*130));rider.vy+=850*dt;rider.x+=rider.vx*dt;rider.y+=rider.vy*dt;rider.onGround=false;let gy=groundY(rider.x);if(rider.y+25>=gy){if(rider.vy>180&&!rider.onGround&&Math.abs(rider.spin)>1){stunts++;score+=Math.abs(Math.round(rider.spin))*500}rider.y=gy-25;rider.vy=0;rider.onGround=true;rider.angle+=(0-rider.angle)*.25;rider.spin=0}else{rider.angle+=(lean*2.7)*dt;rider.spin+=lean*dt*2.4}score+=rider.vx*dt*.25;if(rider.y>H+100){rider.x=90;rider.y=300;rider.vy=0;rider.vx=50}}
function finish(){running=false;document.getElementById('final-time').textContent=document.getElementById('time').textContent;document.getElementById('final-score').textContent=String(Math.floor(score)).padStart(6,'0');document.getElementById('finish-message').textContent=`${stunts?stunts+' stunt'+(stunts>1?'s':'')+' and ':''}a seriously fast finish.`;document.getElementById('finish-card').classList.remove('hidden')}
function draw(){ctx.clearRect(0,0,W,H);let grad=ctx.createLinearGradient(0,0,0,H);grad.addColorStop(0,'#151742');grad.addColorStop(1,'#08091b');ctx.fillStyle=grad;ctx.fillRect(0,0,W,H);drawSky();ctx.save();let cam=Math.max(0,Math.min(rider.x-260,260));ctx.translate(-cam,0);drawTrack();drawObstacles();drawBike();ctx.restore();}
function drawSky(){ctx.fillStyle='#1f2557';for(let i=0;i<8;i++){ctx.beginPath();ctx.arc(90+i*170,110+(i%2)*35,55,Math.PI,0);ctx.fill()}ctx.fillStyle='#363d79';ctx.globalAlpha=.35;for(let i=0;i<30;i++){ctx.fillRect((i*83)%W,100+(i*37)%230,2,2)}ctx.globalAlpha=1}
function drawTrack(){ctx.beginPath();ctx.moveTo(0,470);terrain.forEach(p=>ctx.lineTo(p.x,p.y));ctx.lineTo(1200,600);ctx.lineTo(0,600);ctx.closePath();let g=ctx.createLinearGradient(0,400,0,600);g.addColorStop(0,'#303570');g.addColorStop(1,'#14172f');ctx.fillStyle=g;ctx.fill();ctx.beginPath();terrain.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.strokeStyle='#48f5e5';ctx.lineWidth=5;ctx.shadowBlur=12;ctx.shadowColor='#48f5e5';ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#ff4da6';ctx.lineWidth=2;ctx.setLineDash([8,14]);ctx.stroke();ctx.setLineDash([]);for(let x=0;x<1200;x+=45){ctx.fillStyle='#586091';ctx.fillRect(x,500,25,3)}}
function drawObstacles(){obstacles.forEach(o=>{ctx.fillStyle='#ff4da6';ctx.shadowColor='#ff4da6';ctx.shadowBlur=15;ctx.fillRect(o.x,o.y,o.w,o.h);ctx.shadowBlur=0;ctx.fillStyle='#24284f';ctx.fillRect(o.x+6,o.y+5,o.w-12,5)})}
function drawBike(){ctx.save();ctx.translate(rider.x,rider.y);ctx.rotate(rider.angle);ctx.shadowColor='#48f5e5';ctx.shadowBlur=13;ctx.strokeStyle='#101226';ctx.lineWidth=7;ctx.beginPath();ctx.arc(-24,22,15,0,Math.PI*2);ctx.arc(27,22,15,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#48f5e5';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(-24,22);ctx.lineTo(-5,-2);ctx.lineTo(27,22);ctx.lineTo(9,-5);ctx.lineTo(-24,22);ctx.moveTo(-5,-2);ctx.lineTo(9,-5);ctx.stroke();ctx.fillStyle='#ff4da6';ctx.fillRect(-4,-19,19,6);ctx.strokeStyle='#f5f6ff';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(3,-14);ctx.lineTo(-1,4);ctx.lineTo(15,16);ctx.moveTo(4,-12);ctx.lineTo(20,-1);ctx.stroke();ctx.fillStyle='#ffc7e3';ctx.beginPath();ctx.arc(5,-25,9,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111329';ctx.beginPath();ctx.arc(3,-27,10,Math.PI,Math.PI*1.8);ctx.fill();ctx.restore()}
window.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight',' ','Space'].includes(e.key))e.preventDefault();keys[e.key]=true;if(e.key.toLowerCase()==='r')startGame()});window.addEventListener('keyup',e=>keys[e.key]=false);document.getElementById('start').onclick=startGame;document.getElementById('play-again').onclick=startGame;document.getElementById('restart').onclick=startGame;reset();draw();
